inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-minitest
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

Rails:
  Enabled: true

# Mongoid documents don't use ApplicationRecord
Rails/ApplicationRecord:
  Enabled: false
