FROM ruby:3.2.8-slim

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
      build-essential libmagickwand-dev libyaml-dev curl git && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN gem install bundler && bundle install

COPY . .

EXPOSE 3000

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
