development:
  clients:
    default:
      database: ufosightings
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: sightings_test
      hosts:
        - localhost:27017
      options:
        max_retries: 1
        retry_interval: 0
  options:
    raise_not_found_error: false

production:
  clients:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
  options:
    raise_not_found_error: false
